version: "3.8"

services:
  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_api
    ports:
      - "9090:80"
    volumes:
      - ./app:/var/www/html
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
    tty: true
